project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

import sample.views

urlpatterns = [
    path("", include("sample.urls")),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = sample.views.Handle400View.as_view()
handler403 = sample.views.Handle403View.as_view()
handler404 = sample.views.Handle404View.as_view()
handler500 = sample.views.handle500_view

sample/urls.py
from django.urls import path

from sample import views

app_name = "sample"


urlpatterns = [
    path("", views.LandingView.as_view(), name="landing"),
    path("error/<int:code>", views.ErrorView.as_view(), name="error"),
    path("protected/", views.ProtectedView.as_view(), name="protected"),
]

sample/models.py
import uuid
from typing import Any

from django.conf import settings
from django.db import models
from django.db.models import signals
from django.dispatch import receiver


class UserExtension(models.Model):
    """
    Additional user information
    """

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name="extension",
    )
    uuid = models.UUIDField(
        max_length=64,
        default=uuid.uuid4,
        editable=False,
    )
    verified = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


@receiver(signals.post_save, sender=settings.AUTH_USER_MODEL)
def create_or_save_user_extension(
    sender: settings.AUTH_USER_MODEL,
    instance: settings.AUTH_USER_MODEL,
    created: bool,
    **kwargs: Any,
) -> None:
    if created:
        UserExtension.objects.create(user=instance)
    else:
        instance.extension.save()

sample/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext, gettext_lazy


class RegisterForm(UserCreationForm):
    username = forms.CharField(
        label="Username",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        help_text=gettext_lazy("Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."),
    )
    first_name = forms.CharField(
        label="First name", widget=forms.TextInput(attrs={"class": "form-control"}), required=True
    )
    last_name = forms.CharField(
        label="Last name", widget=forms.TextInput(attrs={"class": "form-control"}), required=True
    )
    email = forms.CharField(
        label="Email address", widget=forms.EmailInput(attrs={"class": "form-control"}), required=True
    )
    password1 = forms.CharField(
        label=gettext_lazy("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class": "form-control"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=gettext_lazy("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class": "form-control"}),
        strip=False,
        help_text=gettext_lazy("Enter the same password as before, for verification."),
    )

    class Meta:
        model = get_user_model()
        fields = ("username", "first_name", "last_name", "email")

    def clean_email(self) -> str:
        email = self.cleaned_data.get("email")
        if get_user_model().objects.filter(email=email).exists():
            raise ValidationError(gettext("Email already exists!"), code="email_exists")
        return email

sample/views.py
from http import HTTPStatus
from typing import Any

from django import http
from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import TemplateView


class LandingView(TemplateView):
    template_name = "sample/landing.html"


@method_decorator(login_required, name="dispatch")
class ProtectedView(TemplateView):
    template_name = "sample/protected.html"


class CleanUpView(View):
    def get(self, request: WSGIRequest) -> HttpResponse:
        # do something
        return HttpResponse(status=HTTPStatus.NO_CONTENT)


class HandleErrorView(TemplateView):
    template_name = "sample/error.html"
    error: HTTPStatus

    def get(self, request: WSGIRequest, *args: Any, **kwargs: Any) -> TemplateResponse:
        context = self.get_context_data(**kwargs)
        return self.render_to_response({**context, "error": self.error}, status=self.error)


class Handle400View(HandleErrorView):
    error = HTTPStatus.BAD_REQUEST


class Handle403View(HandleErrorView):
    error = HTTPStatus.FORBIDDEN


class Handle404View(HandleErrorView):
    error = HTTPStatus.NOT_FOUND


class Handle500View(HandleErrorView):
    error = HTTPStatus.INTERNAL_SERVER_ERROR


def handle500_view(request: WSGIRequest) -> http.HttpResponse:
    return Handle500View.as_view()(request)


class ErrorView(View):
    """
    This is only used for manual testing of error handlers.
    """

    @staticmethod
    def get(request: WSGIRequest, **kwargs: Any) -> None:  # pragma: no cover
        from django.core import exceptions

        code: int = kwargs.get("code", 0)
        raise {400: exceptions.BadRequest, 403: exceptions.PermissionDenied, 404: http.Http404}.get(code, Exception)

sample/views/errors.py
from http import HTTPStatus
from typing import Any

from django import http
from django.core.handlers.wsgi import WSGIRequest
from django.template.response import TemplateResponse
from django.views import View
from django.views.generic import TemplateView


class HandleErrorView(TemplateView):
    template_name = "sample/error.html"
    error: HTTPStatus

    def get(self, request: WSGIRequest, *args: Any, **kwargs: Any) -> TemplateResponse:
        context = self.get_context_data(**kwargs)
        return self.render_to_response({**context, "error": self.error}, status=self.error)


class Handle400View(HandleErrorView):
    error = HTTPStatus.BAD_REQUEST


class Handle403View(HandleErrorView):
    error = HTTPStatus.FORBIDDEN


class Handle404View(HandleErrorView):
    error = HTTPStatus.NOT_FOUND


class Handle500View(HandleErrorView):
    error = HTTPStatus.INTERNAL_SERVER_ERROR


def handle500_view(request: WSGIRequest) -> http.HttpResponse:
    return Handle500View.as_view()(request)


class ErrorView(View):
    """
    This is only used for manual testing of error handlers.
    """

    @staticmethod
    def get(request: WSGIRequest, **kwargs: Any) -> None:  # pragma: no cover
        from django.core import exceptions

        code: int = kwargs.get("code", 0)
        raise {400: exceptions.BadRequest, 403: exceptions.PermissionDenied, 404: http.Http404}.get(code, Exception)

sample/templates/sample/base.html
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha256-T/zFmO5s/0aSwc6ics2KLxlfbewyRz6UNw1s3Ppf5gE=" crossorigin="anonymous">

    {% block title %}
        <title>Docker+Django Template</title>
    {% endblock %}
    <style>
        .navbar-nav {
            font-size: 1rem !important;
        }

        ul.errorlist {
            list-style-type: none;
            padding: 0;
            margin: 0;
            color: red;
        }

        .helptext ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }
    </style>
    {% block styles %}
    {% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark px-5">
    <a class="navbar-brand" href="{% url "sample:landing" %}">Docker+Django Template</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        </ul>
        <ul class="navbar-nav ml-auto">
            {% block navbar %}
                {% if request.user.is_authenticated %}
                    <li>
                        <a class="nav-link" href="{% url "account_logout" %}">{% translate "Logout" %}</a>
                    </li>
                {% else %}
                    <li>
                        <a class="nav-link" href="{% url "account_login" %}">{% translate "Login" %}</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url "account_signup" %}">{% translate "Register" %}</a>
                    </li>
                {% endif %}
            {% endblock %}
        </ul>
    </div>
</nav>

{% block container %}
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha256-/ijcOLwFf26xEYAjW75FizKVo5tnTYiQddPZoLUHHZ8=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha256-7dA7lq5P94hkBsWdff7qobYkp9ope/L5LQy2t/ljPLo=" crossorigin="anonymous"></script>

{% block scripts %}
{% endblock %}
</body>
</html>

sample/templates/sample/error.html
{% extends "sample/base.html" %}
{% load i18n %}

{% block container %}
    <div class="container-fluid">
        <div class="row px-5" style="height: calc(100vh - 54px);">
            <div class="col-lg-12 col-sm-12 justify-content-center align-self-center">
                <h1>{{ error.value }} {{ error.phrase }}</h1>
                <p>{{ error.description }}</p>
            </div>
            <div class="col">
            </div>
        </div>
    </div>
{% endblock %}

sample/templates/sample/landing.html
{% extends "sample/base.html" %}
{% load i18n %}
{% load static %}]

{% block container %}
    <div class="container-fluid">
        <div class="row px-5" style="height: calc(100vh - 54px);">
            <div class="col-lg-5 col-sm-12 justify-content-center align-self-center">
                <h2>Docker+Django Template</h2>
            </div>
            <div class="col">
            </div>
        </div>
    </div>
{% endblock %}

sample/templates/sample/login.html
{% extends "sample/base.html" %}
{% load i18n %}

{% block navbar %}
    <li>
        <a class="nav-link" href="{% url "sample:register" %}">{% translate "Register" %}</a>
    </li>
{% endblock %}

{% block styles %}
    <style>
        .table-borderless td, .table-borderless th {
            border: none;
        }
    </style>
{% endblock %}

{% block container %}
    <div class="container-fluid">
        <div class="row px-5" style="height: calc(100vh - 54px);">
            <div class="col-lg-5 col-sm-12 justify-content-center align-self-center">
                <h2>{% translate "Login" %}</h2>
                <form method="post">
                    {% csrf_token %}
                    <table class="table table-borderless">
                        {{ form.as_table }}
                    </table>
                    <button type="submit" class="btn btn-info" role="button">{% translate "Login" %}</button>
                </form>
            </div>
            <div class="col">
            </div>
        </div>
    </div>
{% endblock %}

sample/templates/sample/protected.html
{% extends "sample/base.html" %}
{% load i18n %}
{% load static %}

{% block container %}
    <div class="container-fluid">
        <div class="row px-5" style="height: calc(100vh - 56px);">
            <div class="col-lg-5 col-sm-12 justify-content-center align-self-center">
                <h2>{% translate "You are logged in as" %} {{ request.user.username }}.</h2>
            </div>
            <div class="col">
            </div>
        </div>
    </div>
{% endblock %}

sample/templates/sample/register.html
{% extends "sample/base.html" %}
{% load i18n %}

{% block styles %}
    <style>
        .table-borderless td, .table-borderless th {
            border: none;
        }
    </style>
{% endblock %}

{% block container %}
    <div class="container-fluid">
        <div class="row px-5" style="margin-top: 50px; margin-bottom: 50px;">
            <div class="col-lg-12 col-sm-12 justify-content-center align-self-center">
                <h2>{% translate "Register" %}</h2>
                <form method="post">
                    {% csrf_token %}
                    <table class="table table-borderless">
                        {{ form.as_table }}
                    </table>
                    <button type="submit" class="btn btn-info" role="button">{% translate "Register" %}</button>
                </form>
            </div>
            <div class="col">
            </div>
        </div>
    </div>
{% endblock %}